sudo: required 
language: generic
services: 
 - docker

before_install: 
 - docker build -t joenid/react-test -f ./client/Dockerfile.dev ./client

script: 
 - docker run -e CI=true joenid/react-test npm test

after_success:
 - docker build -t joenid/multi-client ./client
 - docker build -t joenid/multi-nginx ./nginx
 - docker build -t joenid/multi-server ./server
 - docker build -t joenid/multi-worker ./worker
 #login to docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #take those images and push them to docker hub 
 - docker push joenid/multi-client
 - docker push joenid/multi-nginx
 - docker push joenid/multi-server
 - docker push joenid/multi-worker
